### PR TITLE
Extending the edp2 tools for evaluation of fuzzy thresholds

### PR DESCRIPTION
**Pull request by Toastkanone**
This extension offers the ability to evaluate Service Level Objectives with fuzzy thresholds by adding a mappers package in edp2.

This work is part of a Bachelor 'Fachstudie', which was done at the Reliable Software Systems Group at the University of Stuttgart.

### CODE REVIEW

**Comment by seiferma** [comment]
Thanks for your pull request. Could you please give us the Github handle of your advisor? He/she should be the first one to have a look at the pull request.

**Comment by Toastkanone** [comment]
Hello Mr. Seifermann


our advisor is Floriment Klinaku (https://github.com/klinakuf).


Regards,

Manuel Marroquin

________________________________
Von: Stephan Seifermann <notifications@github.com>
Gesendet: Donnerstag, 24. Oktober 2019 18:28:27
An: PalladioSimulator/Palladio-Addons-ServiceLevelObjectives
Cc: Marroquin Krebs, Manuel Marcos; Author
Betreff: Re: [PalladioSimulator/Palladio-Addons-ServiceLevelObjectives] Extending the edp2 tools for evaluation of fuzzy thresholds (#4)


Thanks for your pull request. Could you please give us the Github handle of your advisor? He/she should be the first one to have a look at the pull request.

**Review by klinakuf — CHANGES_REQUESTED** [review]
Initially, could you please:
- Get rid of the binaries, we don't want them to version. 
- add .gitignore with /bin/ as a content in the edp2 bundle so that the location is always ignored.
- Further, some classes that were added need to be documented properly.

**Review by snowball77 — DISMISSED** [review]
Looks good to me

**Comment by seiferma** [comment]
I kindly ask to delay the merging until the PCM 4.2 release.

**Review by klinakuf — APPROVED** [review]

**Pull request merged**
